GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "jsmith",
    "password": "pass123"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpzbWl0aCIsImlkIjoiNjZlZGVjYTUxNDNlZTAzMGU4MDIyM2NiIiwiaWF0IjoxNzI3MDE1MTk5fQ.q58jvWN-F7GM53Tx-z-ts-OgJQCAvfFD5qS_ae8HCP8

{
    "title": "Title Here",
    "author": "Author Here",
    "url": "www.google.com",
    "userId": "66edeca5143ee030e80223cb",
    "likes": "352"
}

###

DELETE  http://localhost:3003/api/blogs/66f021e89d2ca694d36bbd73
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpzbWl0aCIsImlkIjoiNjZlZGVjYTUxNDNlZTAzMGU4MDIyM2NiIiwiaWF0IjoxNzI3MDE1MTk5fQ.q58jvWN-F7GM53Tx-z-ts-OgJQCAvfFD5qS_ae8HCP8

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "jsmith",
    "name": "John Smith",
    "password": "pass123"
}